---
language: node_js

node_js:
  - "stable"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run check && npm run lint
